### ISSUE TITLE
Zabbix-Meraki-Discovery

### ISSUE THREAD

**Issue by ManchM** [jack-valko/Zabbix-Meraki-Discovery#16] opened 2022-01-11 18:07 UTC
Imported the template and haven't changed anything from the script and I applied the template throughout one of our proxies and I keep getting this error:

Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:50) preventsyield

**Comment by jack-valko** [comment] 2022-01-15 22:29
How large is your Meraki fleet?

**Comment by ManchM** [comment] 2022-01-17 15:37
mor then 250

**Comment by jack-valko** [comment] 2022-01-18 03:09
[ManchM-Beta-Discovery.zip](https://github.com/jack-valko/Zabbix-Meraki-Discovery/files/7885919/ManchM-Beta-Discovery.zip)
The file enclosed may have a fix for execution timeout problem.  I do not have a large Meraki network so I can't be sure this will address the problem, but if you're willing to give it a go it might work for you.  You should delete all Meraki templates and Meraki Hosts before importing this template.  Please let me know what happens.

**Comment by ManchM** [comment] 2022-01-18 15:28
Hello, thank you for your reply, this is what I'm getting now

Cannot execute script: undefined return value

**Comment by ManchM** [comment] 2022-01-18 16:17
Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:87) preventsyield

**Comment by jack-valko** [comment] 2022-01-18 17:57
If you see an undefined return value on execution, do you get anything when you test the discovery?  You'll need to reenter your API key.  Let me know if the error is the same.  Thanks.

**Comment by ManchM** [comment] 2022-01-18 18:57
![save](https://user-images.githubusercontent.com/97548738/150001087-b090d2d7-bee0-4c69-a43a-a2fb88595018.jpg)

end when I execute I'm getting this error.

Cannot execute script: undefined return value

**Comment by ManchM** [comment] 2022-01-18 19:42
And then we are getting this error. 

Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:55) preventsyield

**Comment by jack-valko** [comment] 2022-01-18 20:04
Thank you.  Did you mention you are running this template on the zabbix server or proxy?

**Comment by ManchM** [comment] 2022-01-18 21:27
Sorry, not sure if I got the question correct, but I have  Linus server for app, and imported the script on my  front end web interface app.

**Comment by jack-valko** [comment] 2022-01-18 21:55
Ok it sounds like you are running zabbix server only.  Are you running this in cloud?

**Comment by ManchM** [comment] 2022-01-18 22:07
I have one in Azure and  have one in house.

**Comment by jack-valko** [comment] 2022-01-18 22:09
Give me some details on the instance that is failing, I'm assuming it is in-house.  Is it running on vmware?  If so what is the CPU size?  Did you install a Zabbix appliance?

**Comment by ManchM** [comment] 2022-01-18 22:14
Yes it is on VMware, and has 	4 vCPUs, Memory	4 GB, Hard disk 1	10 GB all default config

**Comment by jack-valko** [comment] 2022-01-18 22:37
This seems like it would be sufficient infrastructure to load ~250 objects from the Meraki API.  Thanks for your help to determine what is going on.

Can you confirm how this instance was installed?  Did you install from packages, appliance, or sources?

How many LLD discovery daemons are you running?  Run this command on your server to find out:
```grep LLDProcessors /etc/zabbix/zabbix_server.conf```

What is your latency to the Meraki cloud?  Run this on your server to find out, you'll need to add your Meraki API key:
```time curl -I -ks -H 'X-Cisco-Meraki-API-Key: <API KEY>' https://api-mp.meraki.com/api/v1/organizations```

**Comment by ManchM** [comment] 2022-01-18 22:46
![1](https://user-images.githubusercontent.com/97548738/150030941-f2b439c8-0aec-4fcc-9042-e396ba083958.jpg)
![2](https://user-images.githubusercontent.com/97548738/150030943-959d27e5-0603-4e38-b6da-f3fdf96fb463.jpg)

**Comment by jack-valko** [comment] 2022-01-19 06:49
Thanks for sending me that info it was very helpful.  Here is what I would try next ....

1. Update your zabbix_server.conf in /etc/zabbix.  I had trouble supporting a large number of devices with a default config, you will need to increase your cache and number of pollers.  Here is what I recommend:
```CacheSize=512M``` (this will create enough memory space to hold all of the new devices and their items)
```StartPollers=15``` (with enough pollers you should see fewer timeouts)
```StartHTTPPollers=3```
```StartLLDProcessors=5``` (add a few LLD processors)

2. Restart your zabbix-server:
```systemctl restart zabbix-server```

3. Install new Beta.  This release reduces the amount of processor time required to discover, hopefully it will complete inside of the timeout.  Note that while I couldn't Test the discovery, if I left it alone after an "Execute Now" for about 15 minutes it did complete. And while I occasionally saw a URL timeout error, the next run discovery usually finished ok.  You should delete the old templates and hosts before installing this.
[ManchM-Beta2-Discovery.zip](https://github.com/jack-valko/Zabbix-Meraki-Discovery/files/7894681/ManchM-Beta2-Discovery.zip)

4. Replace your API key.  It leaked during our last conversation, I've removed it from this thread in any case.

Thanks for staying in touch, I think we're making progress.  Cheers.

**Comment by jack-valko** [comment] 2022-01-19 16:43
I found a bug in the last drop.  Please install Beta3.
[ManchM-Beta3-Discovery.zip](https://github.com/jack-valko/Zabbix-Meraki-Discovery/files/7898909/ManchM-Beta3-Discovery.zip)

**Comment by ManchM** [comment] 2022-01-19 17:40
Hello Jack,

I’m making changes but it is not saving, du you know what I need to do after done with changes?

Thank you

**Comment by ManchM** [comment] 2022-01-19 18:32
Thank you Jack,

I did make the changes and now getting this error 

Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'undefined]'

**Comment by jack-valko** [comment] 2022-01-19 19:17
That's a weird one.  I think this can happen when you don't find any Meraki orgs.  I've updated the beta to try to catch this condition, see enclosed.
[ManchM-Beta4-Discovery.zip](https://github.com/jack-valko/Zabbix-Meraki-Discovery/files/7900014/ManchM-Beta4-Discovery.zip)

**Comment by ManchM** [comment] 2022-01-19 20:52
Thank you Jack,
I did use this Beta4, did not get an error but cant see any data or info coming in.

**Comment by jack-valko** [comment] 2022-01-19 21:36
When you attempt to test the discovery does it just time out?

**Comment by ManchM** [comment] 2022-01-19 21:40
Jack, I can see the date now, it is coming slowly, will update you when it is done.

**Comment by jack-valko** [comment] 2022-01-19 21:41
Good news!  Please keep me in the loop.  And THANK YOU!!

**Comment by ManchM** [comment] 2022-01-20 16:22
Hello Jack,

Good news, I can see all info now. Only thing is it is getting all connection info too, is there a way to get info about Meraki only? 
because right now it gets all connected Wi-Fi machines info too.

**Comment by jack-valko** [comment] 2022-01-20 19:41
This is an interesting result.  The discovery process only looks at the meraki dashboard api, so any device not on the dashboard wont be discoverable.  Can you post a screenshot of items from a device in question?  Is it possible it was discovered in another way?  Thank you.

**Comment by ManchM** [comment] 2022-01-20 20:47
Sure, her is it, yes it is coming with Meraki discovery 
![Mk](https://user-images.githubusercontent.com/97548738/150419670-3252157d-1e0b-4e61-8926-64d7a20266df.jpg)

**Comment by jack-valko** [comment] 2022-01-20 22:02
I'm curious what the discovered items and values are.  Click to Monitoring->Latest Data.  Filter results to one of these hosts and see what data is being gathered.  I'm curious to know if this device reports it is online and what its model number is. Thanks.

**Comment by ManchM** [comment] 2022-01-21 15:23
![mk1](https://user-images.githubusercontent.com/97548738/150552898-1d36b8b7-94ab-455d-9739-7377accdcb2d.jpg)

**Comment by jack-valko** [comment] 2022-01-21 16:40
That is definitely a meraki device, it has a meraki serial number.  I'm not sure why you aren't getting any data, is that the real issue?

**Comment by ManchM** [comment] 2022-01-21 16:48
It says that it is a Latitude which is a laptop, not sure how this data comes in

**Comment by ManchM** [comment] 2022-01-21 16:49
I did noticed, under my System information, there is a err a
![mk2](https://user-images.githubusercontent.com/97548738/150567008-64a43cd1-a99e-4f83-8551-d24fcaff397b.jpg)
bout connection 
Connection timeout of 15 seconds exceeded when connecting to Zabbix server "localhost".

**Comment by jack-valko** [comment] 2022-01-21 18:27
Looks like your server died.  Check the zabbix_server log in /var/log/zabbix for a cause.  Let me know if you think it's related to meraki discovery.

**Comment by jack-valko** [comment] 2022-01-21 18:28
This could also be caused by your zabbix-agent not running on the server.

**Comment by ManchM** [comment] 2022-01-21 19:29
I think so, 
I did restart the server and noting changed, I did run the command got this error

![mk3](https://user-images.githubusercontent.com/97548738/150588600-dc64aa90-ef61-412d-a265-54a184062d47.jpg)

**Comment by jack-valko** [comment] 2022-01-21 19:58
Try these commands to gain an understanding of what your zabbix install is doing:
```more /var/log/zabbix/zabbix_server.log``` (for complete log)
``` tail -f /var/log/zabbix/zabbix_server.log``` (look at the most recent log data, will auto update)
```more /var/log/zabbix/zabbix_agentd.log```
```ps -ef | grep zabbix_server```

**Comment by ManchM** [comment] 2022-01-21 20:13
![mk4](https://user-images.githubusercontent.com/97548738/150593922-88b8c638-298c-4631-8685-609937fb68a7.jpg)
![mk5](https://user-images.githubusercontent.com/97548738/150593925-65a95b6b-c95f-4068-a581-2539cc41af58.jpg)

**Comment by jack-valko** [comment] 2022-01-21 20:50
Your system looks sick.  Try this:
```getenforce```
If the result is 'Enforcing' run this command:
```setenforce 0```
Update your /etc/selinux/config file so SELINUX=disabled then restart zabbix server and zabbix agent.

If getenforce returns 'permissive' or 'disabled' you should escalate to a linux admin who can access to this system for further troubleshooting.

**Comment by ManchM** [comment] 2022-01-21 21:07
I tried to run the commands but is comes back as  
[root@appliance ~]# getenforce
-bash: getenforce: command not found

**Comment by jack-valko** [comment] 2022-01-22 18:13
Ok it looks like the appliance doesn't include selinux.

I've enclosed what a healthy zabbix_server process list looks like.  You need some zabbix admin help that's beyond the scope of the meraki discovery.  

I think we've at least resolved the issue with the discovery not running on large meraki networks so I'm going to close this ticket.  Thank you again for all of your help and good luck getting your system issue resolved.

<img width="1232" alt="Screen Shot 2022-01-22 at 10 09 26 AM" src="https://user-images.githubusercontent.com/83570325/150650489-28344982-6e7e-4f0f-bac9-631ba6196439.png">

**Closed by jack-valko** 2022-01-22 18:13 UTC

**Comment by ManchM** [comment] 2022-01-31 20:38
Hello Jack,

I was able to fix all my issues with Zabbix, but now I'm having issues with the script
please see the attached error. 

Cannot execute script: Error: cannot get URL: Timeout was reached.
at [anon] (httprequest.c:325) internal
at [anon] () native strict preventsyield
at [anon] (function:76) preventsyield
