### ISSUE TITLE
script error 

### ISSUE THREAD

**Issue by ManchM** [jack-valko/Zabbix-Meraki-Discovery#17] opened 2022-01-12 16:02 UTC
Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:81) preventsyield

**Comment by ManchM** [comment] 2022-01-12 17:23
after running this commend I got this error message
 
zabbix_server --runtime-control log_level_increase="lld worker"


Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:51) preventsyield

**Comment by ManchM** [comment] 2022-01-13 17:59
now getting 

Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:62) preventsyield

and 

Cannot execute script: RangeError: execution timeout
at [anon] (duktape.c:77915) internal
at [anon] (function:61) preventsyield

**Comment by jack-valko** [comment] 2022-01-15 22:31
This is a duplicate of issue #16

**Closed by jack-valko** 2022-01-15 22:31 UTC
